######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 24 23:57:26 2017
######################################################################

QT += network
QT += core
QMAKE_CXXFLAGS += -std=c++11

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = raspberry_dzik
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Robot.h
SOURCES += main.cpp Robot.cpp
LIBS += -lwiringPi 

